### ISSUE TITLE
[Feature request]: nextjs14 support

### ISSUE THREAD

**Issue by cheesycod** [DuCanhGH/next-pwa#114] opened 2023-11-18 06:49 UTC
### Describe the feature you'd like to request

nextjs14 support

### Describe the solution you'd like

Add support for nextjs 14

### Describe alternatives you've considered

...

**Comment by DuCanhGH** [comment] 2023-11-18 08:27
This issue is just not helpful. You did not provide any detail, nor did you provide a reproduction. I just have no way to reproduce this, as the package seems to work fine with `next@14` in my case.

**Comment by andrewdoro** [comment] 2023-11-21 15:28
Deploying to Vercel gave me this error Next 14
<img width="1226" alt="Screenshot 2023-11-21 at 17 27 44" src="https://github.com/DuCanhGH/next-pwa/assets/17547035/0452809c-99a4-47f6-9beb-0694e5fda7b9">

**Comment by DuCanhGH** [comment] 2023-11-21 15:31
@andrewdoro please provide a reproduction. Our documentation website also uses `next@14` and deploys to Vercel, and everything is working just fine.

**Comment by andrewdoro** [comment] 2023-11-21 21:14
Nevermind, the error was coming from a corrupt bun.lock

**Comment by DuCanhGH** [comment] 2023-12-08 12:17
I'm going to close this issue, since there's no cooperation from the other end. Do open another issue if you need help! Remember to fill out the details more elaborately next time though.

**Closed by DuCanhGH** 2023-12-08 12:17 UTC
Labels: triage, feature-request, reproduction-needed
