### ISSUE TITLE
Error when navigate offline on mobile

### ISSUE THREAD

**Issue by Wilfried02** [DuCanhGH/next-pwa#66] opened 2023-07-27 16:40 UTC
please i have this error when i try to navigate in my app on mobile offline

Failed to fetch RSC payload. Falling back to browser navigation. TypeError: Failed to fetch

please help me

**Comment by DuCanhGH** [comment] 2023-08-06 09:41
If the app works then you don't really need to care about that. I did see those logs when I tested an app in offline mode, too, but it worked well in the end, as in the app's features still worked just fine. This is because RSC payloads are cached as they are prefetched/requested. Note that the app would not work if you hadn't made any request to those payloads (by visiting their pages or letting Next prefetch them by hovering over `next/link` components) prior to that.

**Comment by Wilfried02** [comment] 2023-08-06 13:24
no, the application does not work on mobile, I have these errors

Le dim. 6 août 2023 à 10:41, Ngô Đức Anh ***@***.***> a
écrit :

**Comment by DuCanhGH** [comment] 2023-08-06 15:26
@Wilfried02 can you provide a reproduction? I'll look into it when I have the time. If your app works fine, you can just ignore those error logs. Just repeating what I said earlier.

**Comment by DuCanhGH** [comment] 2023-12-08 12:19
I'm going to close this issue, since there's no cooperation from the other end. Do open another issue/discussion if you need help! Remember to fill out the details more elaborately next time though.

**Closed** 2023-12-08 12:19 UTC
Labels: bug, triage
